# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: simple.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='simple.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x0csimple.proto\"[\n\x0eSimpleMessage1\x12\x14\n\x0clucky_number\x18\x01 \x02(\x05\x12\x16\n\x0eunlucky_number\x18\x02 \x02(\x05\x12\x1b\n\x05\x65num1\x18\x03 \x02(\x0e\x32\x0c.SimpleEnum1\"i\n\x0eSimpleMessage2\x12\x16\n\x0eunlucky_number\x18\x01 \x01(\x03\x12\x14\n\x0clucky_number\x18\x02 \x01(\x03\x12\x1b\n\x05\x65num1\x18\x03 \x01(\x0e\x32\x0c.SimpleEnum2\x12\x0c\n\x04\x62yte\x18\x04 \x01(\x0c\"\x8c\x01\n\x0cSimpleNested\x12 \n\x07nested1\x18\x01 \x01(\x0b\x32\x0f.SimpleMessage1\x12 \n\x07nested2\x18\x02 \x02(\x0b\x32\x0f.SimpleMessage2\x12\x1b\n\x05\x65num1\x18\x03 \x02(\x0e\x32\x0c.SimpleEnum1\x12\x1b\n\x05\x65num2\x18\x04 \x02(\x0e\x32\x0c.SimpleEnum2\"@\n\x0eSimpleRepeated\x12\x0c\n\x04text\x18\x01 \x03(\t\x12 \n\x07message\x18\x02 \x03(\x0b\x32\x0f.SimpleMessage1\"g\n\x0bSimpleOneof\x12\x1f\n\x04msg1\x18\x01 \x01(\x0b\x32\x0f.SimpleMessage1H\x00\x12\x18\n\x0eunlucky_number\x18\x02 \x01(\x05H\x00\x12\x11\n\tnotnested\x18\x03 \x02(\x03\x42\n\n\x08oneofmsg*\x1f\n\x0bSimpleEnum1\x12\x07\n\x03ONE\x10\x01\x12\x07\n\x03TWO\x10\x02*%\n\x0bSimpleEnum2\x12\n\n\x06ONEONE\x10\x01\x12\n\n\x06TWOTWO\x10\x02')
)

_SIMPLEENUM1 = _descriptor.EnumDescriptor(
  name='SimpleEnum1',
  full_name='SimpleEnum1',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ONE', index=0, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TWO', index=1, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=530,
  serialized_end=561,
)
_sym_db.RegisterEnumDescriptor(_SIMPLEENUM1)

SimpleEnum1 = enum_type_wrapper.EnumTypeWrapper(_SIMPLEENUM1)
_SIMPLEENUM2 = _descriptor.EnumDescriptor(
  name='SimpleEnum2',
  full_name='SimpleEnum2',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ONEONE', index=0, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TWOTWO', index=1, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=563,
  serialized_end=600,
)
_sym_db.RegisterEnumDescriptor(_SIMPLEENUM2)

SimpleEnum2 = enum_type_wrapper.EnumTypeWrapper(_SIMPLEENUM2)
ONE = 1
TWO = 2
ONEONE = 1
TWOTWO = 2



_SIMPLEMESSAGE1 = _descriptor.Descriptor(
  name='SimpleMessage1',
  full_name='SimpleMessage1',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lucky_number', full_name='SimpleMessage1.lucky_number', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='unlucky_number', full_name='SimpleMessage1.unlucky_number', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='enum1', full_name='SimpleMessage1.enum1', index=2,
      number=3, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=107,
)


_SIMPLEMESSAGE2 = _descriptor.Descriptor(
  name='SimpleMessage2',
  full_name='SimpleMessage2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='unlucky_number', full_name='SimpleMessage2.unlucky_number', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lucky_number', full_name='SimpleMessage2.lucky_number', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='enum1', full_name='SimpleMessage2.enum1', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='byte', full_name='SimpleMessage2.byte', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=109,
  serialized_end=214,
)


_SIMPLENESTED = _descriptor.Descriptor(
  name='SimpleNested',
  full_name='SimpleNested',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nested1', full_name='SimpleNested.nested1', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nested2', full_name='SimpleNested.nested2', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='enum1', full_name='SimpleNested.enum1', index=2,
      number=3, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='enum2', full_name='SimpleNested.enum2', index=3,
      number=4, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=217,
  serialized_end=357,
)


_SIMPLEREPEATED = _descriptor.Descriptor(
  name='SimpleRepeated',
  full_name='SimpleRepeated',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='SimpleRepeated.text', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='SimpleRepeated.message', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=359,
  serialized_end=423,
)


_SIMPLEONEOF = _descriptor.Descriptor(
  name='SimpleOneof',
  full_name='SimpleOneof',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg1', full_name='SimpleOneof.msg1', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='unlucky_number', full_name='SimpleOneof.unlucky_number', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='notnested', full_name='SimpleOneof.notnested', index=2,
      number=3, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='oneofmsg', full_name='SimpleOneof.oneofmsg',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=425,
  serialized_end=528,
)

_SIMPLEMESSAGE1.fields_by_name['enum1'].enum_type = _SIMPLEENUM1
_SIMPLEMESSAGE2.fields_by_name['enum1'].enum_type = _SIMPLEENUM2
_SIMPLENESTED.fields_by_name['nested1'].message_type = _SIMPLEMESSAGE1
_SIMPLENESTED.fields_by_name['nested2'].message_type = _SIMPLEMESSAGE2
_SIMPLENESTED.fields_by_name['enum1'].enum_type = _SIMPLEENUM1
_SIMPLENESTED.fields_by_name['enum2'].enum_type = _SIMPLEENUM2
_SIMPLEREPEATED.fields_by_name['message'].message_type = _SIMPLEMESSAGE1
_SIMPLEONEOF.fields_by_name['msg1'].message_type = _SIMPLEMESSAGE1
_SIMPLEONEOF.oneofs_by_name['oneofmsg'].fields.append(
  _SIMPLEONEOF.fields_by_name['msg1'])
_SIMPLEONEOF.fields_by_name['msg1'].containing_oneof = _SIMPLEONEOF.oneofs_by_name['oneofmsg']
_SIMPLEONEOF.oneofs_by_name['oneofmsg'].fields.append(
  _SIMPLEONEOF.fields_by_name['unlucky_number'])
_SIMPLEONEOF.fields_by_name['unlucky_number'].containing_oneof = _SIMPLEONEOF.oneofs_by_name['oneofmsg']
DESCRIPTOR.message_types_by_name['SimpleMessage1'] = _SIMPLEMESSAGE1
DESCRIPTOR.message_types_by_name['SimpleMessage2'] = _SIMPLEMESSAGE2
DESCRIPTOR.message_types_by_name['SimpleNested'] = _SIMPLENESTED
DESCRIPTOR.message_types_by_name['SimpleRepeated'] = _SIMPLEREPEATED
DESCRIPTOR.message_types_by_name['SimpleOneof'] = _SIMPLEONEOF
DESCRIPTOR.enum_types_by_name['SimpleEnum1'] = _SIMPLEENUM1
DESCRIPTOR.enum_types_by_name['SimpleEnum2'] = _SIMPLEENUM2
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SimpleMessage1 = _reflection.GeneratedProtocolMessageType('SimpleMessage1', (_message.Message,), dict(
  DESCRIPTOR = _SIMPLEMESSAGE1,
  __module__ = 'simple_pb2'
  # @@protoc_insertion_point(class_scope:SimpleMessage1)
  ))
_sym_db.RegisterMessage(SimpleMessage1)

SimpleMessage2 = _reflection.GeneratedProtocolMessageType('SimpleMessage2', (_message.Message,), dict(
  DESCRIPTOR = _SIMPLEMESSAGE2,
  __module__ = 'simple_pb2'
  # @@protoc_insertion_point(class_scope:SimpleMessage2)
  ))
_sym_db.RegisterMessage(SimpleMessage2)

SimpleNested = _reflection.GeneratedProtocolMessageType('SimpleNested', (_message.Message,), dict(
  DESCRIPTOR = _SIMPLENESTED,
  __module__ = 'simple_pb2'
  # @@protoc_insertion_point(class_scope:SimpleNested)
  ))
_sym_db.RegisterMessage(SimpleNested)

SimpleRepeated = _reflection.GeneratedProtocolMessageType('SimpleRepeated', (_message.Message,), dict(
  DESCRIPTOR = _SIMPLEREPEATED,
  __module__ = 'simple_pb2'
  # @@protoc_insertion_point(class_scope:SimpleRepeated)
  ))
_sym_db.RegisterMessage(SimpleRepeated)

SimpleOneof = _reflection.GeneratedProtocolMessageType('SimpleOneof', (_message.Message,), dict(
  DESCRIPTOR = _SIMPLEONEOF,
  __module__ = 'simple_pb2'
  # @@protoc_insertion_point(class_scope:SimpleOneof)
  ))
_sym_db.RegisterMessage(SimpleOneof)


# @@protoc_insertion_point(module_scope)
