/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5-dev */

#include "simple.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(SimpleMessage1, SimpleMessage1, AUTO)


PB_BIND(SimpleMessage2, SimpleMessage2, AUTO)


PB_BIND(SimpleNested, SimpleNested, AUTO)


PB_BIND(SimpleRepeated, SimpleRepeated, AUTO)


PB_BIND(SimpleOneof, SimpleOneof, AUTO)





